- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Installing php dependencies
  ansible.builtin.apt:
    pkg:
    - lsb-release
    - apt-transport-https
    - ca-certificates

- name: Create destination for PHP
  shell: sudo touch /etc/apt/trusted.gpg.d/php.gpg

- name: Get php URL
  get_url:
    url: https://packages.sury.org/php/apt.gpg
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: Still installing PHP
  shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
  
  
- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Install PHP and dependencies
  ansible.builtin.apt:
    pkg:
    - php
    - libapache2-mod-php
    - php8.1-mysql
    - php8.1-common
    - php8.1-mysql
    - php8.1-xml
    - php8.1-xml
    - php8.1-curl
    - php8.1-gd
    - php8.1-imagick
    - php8.1-cli
    - php8.1-dev
    - php8.1-imap
    - php8.1-mbstring
    - php8.1-opcache
    - php8.1-soap
    - php8.1-zip
    - php8.1-intl
    state: present


- name: Installing Composer 1
  shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: Installing Composer 2
  shell: php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  

- name: Installing Composer 3
  shell: php composer-setup.php
  
- name: Installing Composer 4
  shell: php -r "unlink('composer-setup.php');"
  
- name: Installing Composer 5
  shell: sudo mv composer.phar /usr/local/bin/composer

- name: make composer executable
  file: 
    path: /usr/local/bin/composer
    mode: a+x
    state: file
