---
- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Set hostname
  ansible.builtin.hostname:
    name: server.ktaltproject.me

- name: Set timezone to Africa/Lagos
  timezone:
    name: Africa/Lagos

# - name: Set hostname in hosts file
#   command: mv /home/vagrant/exam/files/hosts /etc/hosts


- name: Copy hosts file
  ansible.builtin.copy:
    src: /home/vagrant/altschool-cloud-exercises/Altschool-Exam/files/hosts
    dest: /etc/hosts
    remote_src: no

- name: Install ufw
  apt: name=ufw state=latest

#- name: Allow SSH with ufw
 # ufw:
  #  rule: allow
   # name: SSH

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

#- name: Allow WWW Full 
 # ufw: 
  #  rule: allow
   # name: 'WWW Full'

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow

- name: Allow all access to tcp port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    
- name: Allow all access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    
- name: Allow all access to tcp port 443
  community.general.ufw:
    rule: allow
    port: '443'

- name: Update System
  apt: upgrade=dist update_cache=yes

- name: Allow port range 20-10000
  community.general.ufw:
    rule: allow
    port: 20:10000
    proto: tcp
    
  
  notify:
    - reload ufw
    
