- name: Upgrade System
  apt: upgrade=dist update_cache=yes

- name: Installing snapd
  apt:
    name: snapd

- name: Installing Core
  community.general.snap:
    name: core

- name: Refreshing Core
  command: snap refresh core

- name: Installing certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Configuring certbot
  shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot

- name: Requesting SSL Certificate
  shell: sudo certbot --apache --agree-tos --redirect -m ekwealorleo@gmail.com -d ktaltproject.me -d www.ktaltproject.me

- name: Copy htaccess new file to ensure mod rewrite
  ansible.builtin.copy:
    src: /home/vagrant/altschool-cloud-exercises/Altschool_exams/files/.htaccess2
    dest: /var/www/ktaltproject/.htaccess
    remote_src: yes

  notify:
    - restart apache2
